### ISSUE TITLE
Allow to disable skipping empty rows/columns at the beginning of the worksheet

### ISSUE THREAD

**Issue by wikiped** [ToucanToco/fastexcel#209]
There is a similar [issue](#200), which is closed without, as it appears, any fix (with v`0.9.1` being actual).

Expected behaviour is outlined in [examples](https://github.com/dimastbk/python-calamine#example) of `python-calamine` for an option `skip_empty_area`:

```python
from python_calamine import CalamineWorkbook

workbook = CalamineWorkbook.from_path("file.xlsx").get_sheet_by_name("Sheet1").to_python(skip_empty_area=False)
# [
# [",  ",  ",  ",  ",  ",  "],
# ["1",  "2",  "3",  "4",  "5",  "6",  "7"],
# ["1",  "2",  "3",  "4",  "5",  "6",  "7"],
# ["1",  "2",  "3",  "4",  "5",  "6",  "7"],
# ]
```

This automatic behavior is kind of surprising when dealing with files with empty parts at the beginning, as the whole rows calculations get confusing. i.e. for `header_row` you have to count rows as they appear (i.e. including empty rows), but for `skip_rows` you have to count as if there are no empty rows, which is clearly not the most user-friendly approach.

Please consider adding an option/parameter to disable default behavor.
Thank you!

**Comment by PrettyWood** [comment]
`header_row` is the row chosen for the header so of course all rows are taken into account.
Once this is set, `skip_rows` is just the number of rows you want to skip for pagination for example. If you needed to add the header row every time, I reckon this would make the API harder to use.

**Comment by wikiped** [comment]
> what is the use case?

In an ETL pipeline incoming Excel files use arbitrary layout (inluding multi-rows headers and/or empty rows between header and the data). The task is to process the files using predefined specs for `first_header_row`, `last_header_row`, `first_data_row` - set by the user once. The user is only dealing with visible Excel row numbering and is not aware of the internals of how the actual processing happens. So if the user sees that the header starts at row 2 and ends at row 2 and data starts at row 4 - the resulting dataframe should start from row 4. currently it does not. Because `skip_rows=1` (based on previous settings) is making dataframe to start from row 5.

**Comment by PrettyWood** [comment]
This requires changes on calamine side. I will try to open a PR soon. Since 0.11 has some nice improvements, we don't want to postpone it even more for that

**Comment by severinh** [comment]
I'm afraid I'm facing the same issue.

Our systems are currently using `python-calamine` with `.to_python(skip_empty_area=False)`.

Whats's the use case: In one of our systems, users specified a row index in their Excel sheet that is of special interest. But we cannot just start reading from that row (with `skip_rows` or `header_row`). We need the data of the entire sheet. And that sheet may contain empty rows at the top. By silently skipping empty rows at the top of the sheet, the sheet we would get out of fastexcel would not line up with the row configuration from the user. That would break the system. I don't like the system for its fragility - but for now we're stuck with it. :)

Hence, for moving to fastexcel, we would need the equivalent of that `skip_empty_area=False` option in `python-calamine`.

**Comment by severinh** [comment]
@PrettyWood I see that you've been working to fix this by adding a `header_row` option to Calamine: https://github.com/tafia/calamine/pull/453. Thanks again. I'd like to understand: Will that then be tied to the `header_row` option of fastexcel?

I'm writing because I worry that this improvement to calamine might not actually solve the problem I have with calamine/fastexcel. It's different from the `skip_empty_area=False` option that `python-calamine` offers. In short, using fastexcel's `header_row` is not an option for us.

Concretely, I have the following need:

Suppose you have the following Excel sheet:
<img width="119" alt="image" src="https://github.com/user-attachments/assets/82e9110e-ea3c-4e12-999b-50cf675f74fd">

I need to convert that Excel file to a Polars DataFrame **exactly** how it is in Excel, where each row of the Excel is a row in the DataFrame, and the DataFrame columns are `__UNNAMED_$X`:

| `__UNNAMED_0` | `__UNNAMED_1` |
|--------|--------|
| `null` | `null` |
| `null` | `null` |
| `a` | `a` |
| `b` | `b` | 

I'd like to be able to do that using `excel_reader.load_sheet_by_name(name, header_row=None)`. But that does not currently work because the two empty rows get lost.

Once https://github.com/tafia/calamine/pull/453 is in and integrated, will it be possible to get the above DataFrame from FastExcel? And if so how? If I understand correctly, using `excel_reader.load_sheet_by_name(name, header_row=0)` will not an option because the first `null` row would the be missing.

**Comment by PrettyWood** [comment]
Indeed what you would want is for fastexcel to not use any row to generate a header.
On calamine side I reckon my feature is ok since there is no real notion of "header" per se.
Setting `header_row = 0` means "i want all the data starting at row 0".
On fastexcel with use the first row to create a header. This could be changed.

We could have `header_row = None` to say there is no header and `header_row = 'auto'` to use default calamine behavior.
Or we keep our current behavior and add `header_row = -1` for example as extra possibility
I'll discuss this with @lukapeschke next week. I reckon your question is another feature request that I'll be happy to tackle quickly. But still it should probably be another issue

**Comment by PrettyWood** [comment]
@severinh The API between fastexcel and calamine is a bit different.
On fastexcel we already have `header_row = None` to say we don't want any header but at the moment you would get

#### `header_row = None`
```
┌──────────────┬──────────────┐
│ __UNNAMED__0 ┆ __UNNAMED__1 │
│ ---          ┆ ---          │
│ str          ┆ f64          │
╞══════════════╪══════════════╡
│ a            ┆ 0.0          │
│ b            ┆ 1.0          │
└──────────────┴──────────────┘
```

#### `header_row` unset
```
┌─────┬─────┐
│ a   ┆ 0   │
│ --- ┆ --- │
│ str ┆ f64 │
╞═════╪═════╡
│ b   ┆ 1.0 │
└─────┴─────┘
```

So the parameter I plan to modify on fastexcel side is `skip_rows`.

```
        :param skip_rows: Specifies how many rows should be skipped after the `header_row`.
                          Any rows before the `header_row` are automatically skipped.
                          If `header_row` is `None`, it skips the number of rows from the
                          start of the sheet.
```

`None` will mean "auto"

-------------------------------------------------------------

So to answer your question you'll be able to do that with `load_sheet(..., header_row=None, skip_rows=0)`
Hope it's clear and I'm not mistaken 🙏

**Comment by PrettyWood** [comment]
Ok thinking again about it I reckon it's a bit weird because with what I suggest we'll get

```
Header row = 0, skip_rows = None
shape: (3, 2)
┌──────────────┬──────────────┐
│ __UNNAMED__0 ┆ __UNNAMED__1 │
│ ---          ┆ ---          │
│ str          ┆ f64          │
╞══════════════╪══════════════╡
│ null         ┆ null         │
│ a            ┆ 0.0          │
│ b            ┆ 1.0          │
└──────────────┴──────────────┘
```

which may seem counterintuitive.
I'll take some time to think about it
